spring:
  datasource:
    username: bloguser
    password: '123456'

logging:
  config: classpath:log4j/log4j2.xml
  level.com.site.blog: debug

upload:
  uploadAuthorImg: "/opt/mini-blog/authorImg/"
  fileUploadDic: "/opt/mini-blog/upload/"
  sqlAuthorImg: "/authorImg/"
  fileSqlDic: "/upload/"

adminLogin: false